apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: python-template-test72624 
  janus-idp.io/tekton: python-template-test72624
  backstage.io/kubernetes-id: python-template-test72624
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: python-template-test72624
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  