apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python-template-test72624
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-template-test72624 
  name: python-template-test72624
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python-template-test72624 
